# Generated by Django 3.0.1 on 2019-12-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profession',
            field=models.CharField(max_length=128, verbose_name='职业'),
        ),
    ]
